<?php
/** @var Magento\Backend\Block\Template $block */
/** @var Magento\Framework\Escaper $escaper */
?>


<div class="form-row">
    <section class="admin__page-section offer-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?= $escaper->escapeHtml(__('Address Information')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <?= $block->getChildHtml() ?>
        </div>
    </section>
</div>
